# see defaults and more at: https://gist.github.com/iuliandita/a4c1dd0e25460af91ebeeef51e0ef7ec
[general]
import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]

[terminal]
shell = "/bin/bash"

[window]
opacity = 0.9

#[font]
#size = 11
