# see defaults and more at: https://gist.github.com/iuliandita/a4c1dd0e25460af91ebeeef51e0ef7ec
import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]

[shell]
program = "/bin/bash"
args = []

[window]
opacity = 0.75

#[font]
#size = 11
